"""add_assistant_conversation_and_message_tables

Revision ID: 1c3cd3e0e845
Revises: b1d80e3d8a71
Create Date: 2026-04-15 21:50:05.852130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '1c3cd3e0e845'
down_revision: Union[str, None] = 'b1d80e3d8a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_conversation_flow_id'), ['flow_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assistant_conversation_org_id'), ['org_id'], unique=False)

    op.create_table('assistant_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('tool_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_message', schema=None) as batch_op:
        batch_op.create_index('ix_assistant_message_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_message_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_message_conversation_id'))
        batch_op.drop_index('ix_assistant_message_conversation_created')

    op.drop_table('assistant_message')
    with op.batch_alter_table('assistant_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_conversation_org_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_conversation_flow_id'))

    op.drop_table('assistant_conversation')
    # ### end Alembic commands ###
