"""make template_metadata.updated_by nullable

Revision ID: 2998418b3bc5
Revises: 6ec028483162
Create Date: 2026-04-19 14:28:20.765617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '2998418b3bc5'
down_revision: Union[str, None] = '6ec028483162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_metadata', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('template_metadata', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_metadata', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    with op.batch_alter_table('component_metadata', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
