"""add template and component metadata

Revision ID: 460a5ee548b6
Revises: 1c3cd3e0e845
Create Date: 2026-04-18 13:37:28.096880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '460a5ee548b6'
down_revision: Union[str, None] = '1c3cd3e0e845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_metadata',
    sa.Column('agent_usage_notes', sa.Text(), nullable=True),
    sa.Column('agent_summary', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_metadata_component_name'), ['component_name'], unique=True)

    op.create_table('template_metadata',
    sa.Column('agent_usage_notes', sa.Text(), nullable=True),
    sa.Column('agent_summary', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_metadata_flow_id'), ['flow_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_metadata_flow_id'))

    op.drop_table('template_metadata')
    with op.batch_alter_table('component_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_metadata_component_name'))

    op.drop_table('component_metadata')
    # ### end Alembic commands ###
