"""create flow_run

Revision ID: 882a95c04213
Revises: b8d0abf646b6
Create Date: 2026-04-15 15:37:50.017817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '882a95c04213'
down_revision: Union[str, None] = 'b8d0abf646b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_run',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('inputs_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('result_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('auto_retry', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_delivery_state', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_run_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_run_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_run_status'), ['status'], unique=False)

    # Compound indexes for common query patterns
    op.create_index('ix_flow_run_org_status_queued_at', 'flow_run', ['organization_id', 'status', 'queued_at'])
    # NOTE: PostgreSQL would use ["flow_id", sa.text("queued_at DESC")] for the index below,
    # but SQLite does not support expression indexes. Using plain column order instead.
    op.create_index('ix_flow_run_flow_queued_at_desc', 'flow_run', ['flow_id', 'queued_at'])
    op.create_index('ix_flow_run_status_heartbeat', 'flow_run', ['status', 'heartbeat_at'])
    op.create_index('ix_flow_run_status_finished', 'flow_run', ['status', 'finished_at'])

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_run_status_finished', 'flow_run')
    op.drop_index('ix_flow_run_status_heartbeat', 'flow_run')
    op.drop_index('ix_flow_run_flow_queued_at_desc', 'flow_run')
    op.drop_index('ix_flow_run_org_status_queued_at', 'flow_run')

    with op.batch_alter_table('flow_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_run_status'))
        batch_op.drop_index(batch_op.f('ix_flow_run_organization_id'))
        batch_op.drop_index(batch_op.f('ix_flow_run_flow_id'))

    op.drop_table('flow_run')
    # ### end Alembic commands ###
