"""create_flow_run_log

Revision ID: b1d80e3d8a71
Revises: 882a95c04213
Create Date: 2026-04-15 15:45:27.944433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1d80e3d8a71'
down_revision: Union[str, None] = '882a95c04213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_run_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(["run_id"], ["flow_run.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_run_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_run_log_run_id'), ['run_id'], unique=False)

    op.create_index("ix_flow_run_log_run_ts", "flow_run_log", ["run_id", "ts"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_flow_run_log_run_ts", table_name="flow_run_log")

    with op.batch_alter_table('flow_run_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_run_log_run_id'))

    op.drop_table('flow_run_log')
    # ### end Alembic commands ###
