#!/usr/bin/env node
/**
 * gen-schemas.mjs — regenerate src/schemas/api/{_generated.ts, generated.meta.ts}
 * from the backend OpenAPI spec.
 *
 * Pipeline:
 *   1. Flatten Pydantic v2 / OpenAPI 3.1 `$defs` into components.schemas
 *      (workaround for openapi-zod-client + json-schema-ref-parser; see
 *      docs/superpowers/research/2026-04-24-phase-1-tooling-block.md).
 *   2. Run openapi-zod-client with --group-strategy none → one big client.ts.
 *   3. Strip the Zodios client boilerplate; keep only the zod schema declarations.
 *      Promote each declaration to `export const`.
 *   4. Parse the original openapi.json for (path, method, tag, operationId)
 *      tuples. Each becomes a schema id `api.<tag>.<operationId>`.
 *   5. Write _generated.ts (all schemas) and generated.meta.ts (the
 *      strict-flag registry, all entries default to "permissive").
 *
 * Usage: node scripts/gen-schemas.mjs <path-to-openapi.json>
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { rewriteV3ToV4 } from "./zod4-postprocessor.mjs";

const [, , openapiPath] = process.argv;
if (!openapiPath) {
  console.error("Usage: gen-schemas.mjs <openapi.json>");
  process.exit(2);
}

const SCRIPTS_DIR = path.dirname(new URL(import.meta.url).pathname);
const FRONTEND_DIR = path.dirname(SCRIPTS_DIR); // src/frontend
const FLATTEN_PY = path.resolve(SCRIPTS_DIR, "flatten-openapi-defs.py");
const OUT_DIR = path.resolve(FRONTEND_DIR, "src/schemas/api");
const TMP_FLAT = path.resolve("/tmp", "openapi-flat.json");
const TMP_CLIENT = path.resolve("/tmp", "openapi-zod-client.ts");

console.log(`[1/5] Flatten $defs → ${TMP_FLAT}`);
execSync(`python3 "${FLATTEN_PY}" "${openapiPath}" "${TMP_FLAT}"`, { stdio: "inherit" });

console.log(`[2/5] Run openapi-zod-client → ${TMP_CLIENT}`);
execSync(
  `npx openapi-zod-client "${TMP_FLAT}" --output "${TMP_CLIENT}" --export-schemas --group-strategy none`,
  { stdio: "inherit", cwd: FRONTEND_DIR },
);

console.log(`[3/5] Extract schema declarations`);
const raw = fs.readFileSync(TMP_CLIENT, "utf8");

const schemasObjMatch = raw.match(/^export const schemas = \{/m);
if (!schemasObjMatch) {
  throw new Error("could not find `export const schemas = {` in generated client");
}
const declarationsEnd = schemasObjMatch.index;

const head = raw.slice(0, declarationsEnd);
const declSection = stripLeadingNonZodLines(head);

// Promote every `const Foo = z.<...>` to `export const Foo = ...`. Drop duplicates
// (the 6 known MCP duplicate-operation-IDs each spawn a duplicate schema name).
const seenDecls = new Set();
const promoted = [];
const declRe = /^(?:export\s+)?const ([A-Za-z_][A-Za-z0-9_]*)\s*=([\s\S]*?);\n(?=(?:export\s+)?const |\nexport const schemas|$)/gm;
let lastEnd = 0;
for (const m of declSection.matchAll(declRe)) {
  promoted.push(declSection.slice(lastEnd, m.index));
  const [, name, body] = m;
  if (seenDecls.has(name)) {
    promoted.push(`// (omitted duplicate declaration of ${name} — see scripts/gen-schemas.mjs dedup)\n`);
  } else {
    seenDecls.add(name);
    promoted.push(`export const ${name} =${body};\n`);
  }
  lastEnd = m.index + m[0].length;
}
promoted.push(declSection.slice(lastEnd));

console.log(`[4/5] Read tags from openapi.json`);
const spec = JSON.parse(fs.readFileSync(openapiPath, "utf8"));
const ids = [];
for (const [pth, ops] of Object.entries(spec.paths || {})) {
  if (typeof ops !== "object" || ops === null) continue;
  for (const [method, op] of Object.entries(ops)) {
    if (typeof op !== "object" || op === null) continue;
    if (!["get", "post", "patch", "put", "delete"].includes(method)) continue;
    const tags = op.tags || ["untagged"];
    const tag = String(tags[0]).toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
    const opId = op.operationId || `${method}_${pth.replace(/[^a-zA-Z0-9]+/g, "_")}`;
    ids.push([`api.${tag}.${opId}`, "permissive"]);
  }
}

console.log(`[5/5] Write ${OUT_DIR}/{_generated.ts, generated.meta.ts}`);
fs.mkdirSync(OUT_DIR, { recursive: true });

const generated = [
  `// AUTO-GENERATED by src/frontend/scripts/gen-schemas.mjs from the backend OpenAPI`,
  `// spec. Do not edit by hand. Run \`make gen_frontend_schemas\` to regenerate.`,
  `//`,
  `// Pre-process: scripts/flatten-openapi-defs.py inlines Pydantic v2 \`$defs\` into`,
  `// components.schemas before passing to openapi-zod-client (which doesn't natively`,
  `// support nested \`$defs\`). See`,
  `// docs/superpowers/research/2026-04-24-phase-1-tooling-block.md.`,
  `//`,
  `// Post-process: scripts/zod4-postprocessor.mjs rewrites v3 idioms`,
  `// (.passthrough(), single-arg z.record, z.nativeEnum) emitted by`,
  `// openapi-zod-client into v4 syntax (z.looseObject, two-arg z.record, z.enum).`,
  `/* eslint-disable */`,
  ``,
  rewriteV3ToV4(promoted.join("")),
].join("\n");
fs.writeFileSync(path.join(OUT_DIR, "_generated.ts"), generated);

const meta = [
  `// AUTO-GENERATED. Edit strict flags per-domain as migrations finish.`,
  `// Total registered schema ids: ${ids.length}.`,
  `import { registerSchema } from "@/lib/schema-registry";`,
  ``,
  `export const SCHEMA_MODES: Array<[string, "permissive" | "strict"]> = [`,
  ...ids.map(([id, mode]) => `  [${JSON.stringify(id)}, ${JSON.stringify(mode)}],`),
  `];`,
  ``,
  `SCHEMA_MODES.forEach(([id, mode]) => registerSchema(id, mode));`,
  ``,
].join("\n");
fs.writeFileSync(path.join(OUT_DIR, "generated.meta.ts"), meta);

const lineCount = generated.split("\n").length;
console.log(
  `Done. _generated.ts: ${lineCount} lines, ${seenDecls.size} unique schema declarations. ` +
  `generated.meta.ts: ${ids.length} registered schema ids across ${new Set(ids.map(([i]) => i.split(".")[1])).size} tags.`,
);

function stripLeadingNonZodLines(src) {
  // Drop only the `import { ... Zodios ... }` line. Top-level `type` aliases are
  // kept — openapi-zod-client emits them for recursive/self-referencing zod schemas
  // via `z.lazy(() => ...): z.ZodType<TheTypeAlias>`. They're plain TS, not Zodios.
  const lines = src.split("\n");
  const out = [];
  for (const ln of lines) {
    if (ln.startsWith("import {") && ln.includes("@zodios/core")) continue;
    out.push(ln);
  }
  return out.join("\n");
}
